# Generated by Django 6.0.4 on 2026-05-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.IntegerField(default=19),
        ),
    ]
